name: Publish Release

on:
    workflow_dispatch:
        inputs:
            scope:
                type: choice
                description: "https://github.com/JavierSegoviaCordoba/semver-gradle-plugin?tab=readme-ov-file#scopes"
                options:
                    - major
                    - minor
                    - patch
                    - auto
                required: true

permissions:
    contents: read

jobs:
    publish-maven:
        runs-on: ubuntu-latest
        environment:
            name: maven-central
            url: https://central.sonatype.com/namespace/org.maplibre.spatialk
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  fetch-tags: true
            - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
              with:
                  distribution: temurin
                  java-version: 21
            - run: |
                  ./gradlew publishAndReleaseToMavenCentral -Psemver.stage=final -Psemver.scope=${{ github.event.inputs.scope }}
              env:
                  ORG_GRADLE_PROJECT_mavenCentralUsername:
                      ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword:
                      ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                  ORG_GRADLE_PROJECT_signingInMemoryKey:
                      ${{ secrets.GPG_PRIVATE_KEY }}
                  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword:
                      ${{ secrets.GPG_PASSPHRASE }}

    publish-pages:
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deploy-pages.outputs.page_url }}
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  fetch-tags: true
            - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
              with:
                  distribution: temurin
                  java-version: 21
            - run: |
                  ./gradlew :mkdocsBuild -Psemver.stage=final -Psemver.scope=${{ github.event.inputs.scope }}
            - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
              with:
                  path: build/mkdocs
            - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
              id: deploy-pages

    tag:
        runs-on: ubuntu-latest
        needs: [publish-maven, publish-pages]
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  fetch-tags: true
            - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
              with:
                  distribution: temurin
                  java-version: 21
            - run: |
                  ./gradlew :createSemverTag -Psemver.stage=final -Psemver.scope=${{ github.event.inputs.scope }}
            - run: git push --follow-tags
